### ISSUE TITLE
Add changes from other repos

### ISSUE THREAD

**Issue by ratzlaff** [ratzlaff/XCom-tools#6]
The network of https://github.com/pmprog/OpenXCOM.Tools seems to have some good history in it plus some bug fixes.

**Comment by ratzlaff** [comment]
master branches from @pmprog, @TheBigSot and @JonnyH have been rebased onto the original code history imported from sourceforge. @kevL has much more history and is still active so I'd like to get things to a point where that can be rebased with a single command and no conflicts. He's got bug fixes and good maintenance going on over there and I'd like to merge that in eventually. 

The current history has been run through multiple invocations of filter-branch to do the following (in no particular order):

- [x] remove MARS.OXC
- [x] remove .gitattributes and simplify .gitignore
  - .gitattributes was preventing most rebase operations from continuing due to the git settings to auto convert line endings when run in a non-windows environment
- [x] remove execute bits
- [x] change all files to unix line endings
- [x] delete all compiled .exe .dll
  - the release history should be managed somewhere else
- [x] remove Visual Studio files
  - people want to work in different environments. There is a premake configuration to generate the build environment of your choosing. There will eventually be a build solution checked in by default for those that do not want to generate their own.
- [x] remove code signing keys
  - that was just something I was pushing buttons on years ago to see what would happen
- [ ] Look at files in the 'old' directories and make sure there was nothing worth keeping.
- [ ] Delete unnecessary files out of DSShared

**Comment by kevL** [comment]
ratzlaff,
if you find that you need clarification if/when going through my chaotic commits, just say and i can hopefully point out the relevant bits.

**Comment by ratzlaff** [comment]
@kevL Thanks for the support! Will do!

**Comment by kevL** [comment]
oh, one thing I noticed (and fixed somewhere) is that the Release config was building against one of the Debug assemblies ... I think i noticed it using this app:

http://mikehadlow.blogspot.ca/2011/02/asmspy-little-tool-to-help-fix-assembly.html

but really i can't remember,

**Comment by ratzlaff** [comment]
That tool looks super useful, thanks for the tip!
for c++ I use [Dependency Walker](http://www.dependencywalker.com) to do the same thing

**Comment by ratzlaff** [comment]
@kevL I have rebased your history into this repo and merged @JonnyH 's linux branch into it - almost starts up on my mac now! Hurray!

Should you be interested in switching the repo you have forked from, your current master branch corresponds to the kevL/master-97e4203 branch

Thanks again!

**Comment by kevL** [comment]
big job! lots to go ...

:)

**Comment by ratzlaff** [comment]
@kevL I put the contents of your Distribution folder as the first release of this project! Honestly I haven't looked at it and seen the differences since I last touched the code. Anything major I should add to the release notes?

**Comment by kevL** [comment]
not really. The major change anyone's going to notice is only the Verdana font ...


I went through my commits and made a list that should help point out significant changes:
http://pastebin.com/Fe5DTaQH

**Comment by kevL** [comment]
@ratzlaff
holy cr*p you put a lot of effort into this. sure I take 'exception' to a bunch of stuff, but the sheer volume is amazing!

"profiles"? no clue.


anyway i'm still working stuff over, and will soon try to implement YAML for data storage. ( YamlDotNet )

**Comment by ratzlaff** [comment]
Heh, thanks!

No worries to the exceptions. I started all this about 2002 (3 years after taking my first CS course at the university) so naturally the code is pretty bad. Looking at it now I am kind of amazed it works 'as well' as it does given that there was no revision control used, no automated testing of any kind and very minimal user testing beyond what would be posted on my (now extinct) website. I would do a number of things very differently today.

Honestly, C# was also still pretty new at the time and I was just excited about not having to write any more java code!

'profiles' was a system I was creating for pckview to map information about a datafile format (width, height, component size) to the specific loaders in the code. As with a lot of the class heirarcy, it was designed on the spot with no real foresight beyond getting something working sooner rather than later. Really it was just a way to add to the 'open files' file list without having to add code to the system.
